Updating pyrkit to work with RNA-seek

diff --git a/pyrkit b/pyrkit
--- a/pyrkit
+++ b/pyrkit
@@ -3,7 +3,7 @@
 # pyrkit: a tool to archive and co-locate NGS data with hierarchical metadata
 set -euo pipefail
 
-VERSION="0.1.0-beta"
+VERSION="0.1.0"
 
 # Functions
 function err() { cat <<< "$@" 1>&2; }
@@ -67,6 +67,34 @@ optional.add_argument('-h', '--help', action='help', default=argparse.SUPPRESS,
 optional.add_argument('--version', action='version',
                     version='%(prog)s $VERSION', help="Display version information and exit")
 EOF
+}
+
+
+function retry() {
+  # Tries to run a cmd 5 times before failing 
+  # If a command is successful, it will break out of attempt loop
+  # Failed attempts are padding with the following exponential 
+  # back-off strategy {4, 16, 64, 256, 1024} in seconds
+  # @INPUTS "$@"" = cmd to run 
+  # @CALLS fatal() if command cannot be run in 5 attempts
+  local n=1
+  local max=5
+  local attempt=true # flag for while loop
+  while $attempt; do
+    # Attempt command and break if successful 
+    "$@" && attempt=false || {
+      # Try again up to 5 times 
+      if [[ $n -le $max ]]; then
+        echo -e "Command failed: $@"
+        delay=$(( 4**$n ))
+        echo -e "Attempt: ${n}/${max}. Trying again in ${delay} seconds!\n"
+        sleep $delay;
+        ((n++))
+      else
+        fatal "Fatal: the command has failed after max attempts!"
+      fi
+    }
+  done
 }
 
 
@@ -141,59 +169,6 @@ function lint(){
 }
 
 
-function _get_inner_distances(){
-  # Parses Inner Distance Maxmia from RSeQC output files
-  # @INPUT $1 = Input Directory or pipeline working directory (i.e. $INPUT_DIRECTORY)
-  # @INPUT $2 = MultiQC Output Directory
-  # @INPUT $3 = Parsed Inner Distance Output file
-
-  # Performant approach to checking if glob exists using a Bash built-in function
-  if compgen -G "${1}/STAR_files/*.Aligned.sortedByCoord.out.inner_distance_freq.txt" > /dev/null; then
-    echo -e "Sample\tInner_Dist_Maxima" > "${2}/${3}" || fatal "Failed to write to MultiQC Directory ${2}"
-    # Get Inner Distance Maxima from RSeQC Output files
-    for f in "${1}"/STAR_files/*.Aligned.sortedByCoord.out.inner_distance_freq.txt; do
-      sample=$(basename "$f" | sed 's/^output.//' | sed 's/.p2.Aligned.sortedByCoord.out.inner_distance_freq.txt$//');
-      inner_dist_maxima=$(sort -k3,3nr "$f" | awk -F '\t' 'NR==1{print $1}');
-      echo -e "${sample}\t${inner_dist_maxima}";
-    done >> "${2}/${3}"
-  fi
-}
-
-
-function _get_median_tin(){
-  # Parses RSeQC Median TIN (transcript integrity number) from output files
-  # @INPUT $1 = Input Directory or pipeline working directory (i.e. $INPUT_DIRECTORY)
-  # @INPUT $2 = MultiQC Output Directory
-  # @INPUT $3 = Parsed medTIN Output file
-
-  # Performant approach to checking if glob exists using a Bash built-in function
-  if compgen -G "${1}/STAR_files/*.summary.txt" > /dev/null; then
-    echo -e "Sample\tmedian_tin" > "${2}/${3}" || fatal "Failed to write to MultiQC Directory ${2}"
-    # Parse medTIN from RSeQC tin.py output files
-    cut -f1,3 "${1}"/STAR_files/*.summary.txt | \
-      grep -v '^Bam_file' | \
-      sed 's/.p2.Aligned.sortedByCoord.out.dmark.bam//g' | \
-      awk -F '\t' '{printf "%s\t%.3f\n", $1,$2}' >> "${2}/${3}"
-  fi
-}
-
-
-function _get_flowcell_lanes(){
-  # Parses Logfile with Information about each FastQ file
-  # @INPUT $1 = Input Directory or pipeline working directory (i.e. $INPUT_DIRECTORY)
-  # @INPUT $2 = MultiQC Output Directory
-  # @INPUT $3 = Parsed Flowcell Lanes Output file
-
-  # Performant approach to checking if glob exists using a Bash built-in function
-  if compgen -G "${1}/rpt.on.fastqs.txt" > /dev/null; then
-    echo -e "Sample\tflowcell_lanes" > "${2}/${3}" || fatal "Failed to write to MultiQC Directory ${2}"
-    # Parse Flowcell Lane Information
-    sed 's/\.R1\.fastq\.gz//g' "${1}/rpt.on.fastqs.txt" | \
-      awk -v OFS='\t' '{print $1,$NF}' >> "${2}/${3}"
-  fi
-}
-
-
 function _get_sample_groups(){
   # Parses sample group information from sample.json (generated by running lint)
   # @INPUT $1 = Input Directory containing sample.json generated by @init()
@@ -216,10 +191,7 @@ function parse(){
   # @INPUT $1 = Input Directory or pipeline working directory (i.e. $INPUT_DIRECTORY)
   # @INPUT $2 = MultiQC Directory (i.e. $MULTIQC_DIRECTORY)
 
-  # Parse Addtional QC metadata from logfiles
-  _get_inner_distances "${1}" "${2}" "mqc_rseqc_inner_distance_plot_Percentages_parsed.txt"
-  _get_median_tin "${1}" "${2}" "rseqc_median_tin.txt"
-  _get_flowcell_lanes "${1}" "${2}" "sample_flowcell_lanes.txt"
+  # Parse Addtional metadata from logfiles
   _get_sample_groups "${1}/DME" "${2}" "sample_group.txt"
 }
 
@@ -233,7 +205,6 @@ function QC(){
   (cd "${2}"; python "${1}" "${2}"/*.txt )
 }
 
-
 function fingerprint(){
   # Generates a Unique Identifer for an Analysis
   # Analysis ID is determinstic and based on user inputs to pipeline
@@ -241,15 +212,40 @@ function fingerprint(){
   # @INPUT $2 = DME base directory for all intermediate output files
   # @RETURNS inputs_md5, analysis_id, assembly_name, gtf_ver
 
-  # runinfo.txt aggregates all important user inputs, fix inconsistent delimiter
-  sed 's/^file /file\t/g' "${1}/runinfo.txt" > "${2}/run_metadata.txt"
+  # run_metadata.txt aggregates all important user inputs and pipeline options
+  local pipeline_version=$(jq .project.version "${1}/config.json" | sed 's/"//g' | sed "s/'//g")
+  local nsamples=$(jq .project.groups.rsamps[] "${1}/config.json" | sed 's/"//g' | sed "s/'//g" | wc -l)
+  local runtype=$(jq .project.nends "${1}/config.json" | sed 's/1/single-end/g' | sed 's/2/paired-end/g')
+  local refjson=$(jq .project.annotation "${1}/config.json" | sed 's/"//g' | sed "s/'//g")
+  local genomefa=$(jq .references.rnaseq.GENOME "$refjson" | sed 's/"//g' | sed "s/'//g")
+  local gtf=$(jq .references.rnaseq.GTFFILE "$refjson" | sed 's/"//g' | sed "s/'//g")
+  local gtf_ver=$(jq .references.rnaseq.ORGANISM "$refjson" | sed 's/"//g' | sed "s/'//g" | awk -F '_' '{print $NF}')
+  local assembly_name=$(jq .references.rnaseq.ORGANISM "$refjson" | sed 's/"//g' | sed "s/'//g" | awk -F '_' '{print $1}')
+  local species=$(jq '.Project."Organism(s)"[]' ${2}/project.json | sed 's/"//g' | sed "s/'//g")
+  local method=$(jq '.Project."Type of Project"[]' ${2}/project.json | sed 's/"//g' | sed "s/'//g")
+
+  echo -e "pipeline_ver\t${pipeline_version}" > "${2}/run_metadata.txt"
+  echo -e "number_of_cases\t${nsamples}" >> "${2}/run_metadata.txt"
+  echo -e "runtype\t${runtype}" >> "${2}/run_metadata.txt"
+  echo -e "method\t${method}" >> "${2}/run_metadata.txt"
+  echo -e "gtf\t${gtf}" >> "${2}/run_metadata.txt"
+  echo -e "gtf_ver\tv${gtf_ver/v}" >> "${2}/run_metadata.txt"
+  echo -e "assembly_name\t${assembly_name}" >> "${2}/run_metadata.txt"
+  echo -e "genomefa\t${genomefa}" >> "${2}/run_metadata.txt"
+  echo -e "species\t${species^}" >> "${2}/run_metadata.txt"
+  
+  for f in "${1}"/*.R?.fastq.gz; do
+    # Find a list of input FastQ files 
+    echo -e "file\t${f}" >> "${2}/run_metadata.txt"
+  done
+
 
   # Convert Input Files to MD5 checksums
   while read -r field value; do
     # Get MD5 checksum if evaluating an input file
     ifile=$(if [[ -f "$value" ]]; then md5sum "$value" | awk '{print $1}'; else echo "$value"; fi)
     echo -e "$field\t$ifile"
-  done < <(grep -v '^jobname\|^gtf_ver\|^assembly_name\|^species' "${2}/run_metadata.txt" | sort -k2,2) \
+  done < <(grep -v '^gtf_ver\|^assembly_name' "${2}/run_metadata.txt" | sort -k2,2) \
   > "${2}/run_inputs.md5"
 
   # Add MD5 checksum of all inputs and create an analysis id to run metadata
@@ -332,9 +328,9 @@ function _sym_link_gbam(){
   # @INPUT $8 = Long Analysis ID (i.e. f63ab9966e22f548934c31172388b750)
   # @INPUT $9 = DME Primary Analysis Collection Path associated with a sample
 
-  for f in "${1}"/STAR_files/*.p2.Aligned.sortedByCoord.out.dmark.bam; do
+  for f in "${1}"/bams/*.star_rg_added.sorted.dmark.bam; do
     # Find a FastQ files mock Sample Collection
-    sample=$(basename "$f" | sed 's/\.p2\.Aligned\.sortedByCoord\.out\.dmark\.bam$//')
+    sample=$(basename "$f" | sed 's/\.star_rg_added\.sorted\.dmark\.bam$//')
     rawdir=$(ls --color=never -d "${2}"/upload/PI_Lab_*/Project_*/Sample_*_"${sample}")
     # Create renamed symlinks with assembly, gtf ver and analysis_id
     ln -s "$f" "${rawdir}/${sample}.${5}_${6}.Aligned.toGenome.sorted.dmark.${7}.bam" \
@@ -436,7 +432,7 @@ function multi(){
 
   # Symlink remaining files to Primary Analysis collection
   mqc_prefix=$(basename "${1}")
-  for f in "${3}"/multiqc_matrix.tsv "${1}/${mqc_prefix}_multiqc_report.html" "${4}"; do
+  for f in "${3}/multiqc_matrix.tsv" "${1}/Reports/multiqc_report.html" "${1}/Reports/RNA_Report.html" "${4}"; do
     ln -s "${f}" "${2}/" || echo "Failed to create symlink for $f and ${2}";
   done
 
@@ -527,14 +523,14 @@ function main(){
   # Creates symlinks for sample-level collections in DME
   links "${INPUT_DIRECTORY%/}" "${output}" "${OUTPUT_VAULT%/}" "${repohome}/src/meta" \
         "${assembly_name}" "${gtf_ver}" "${analysis_id}" "${inputs_md5}" "${dme_analysis_home}"
-
+ 
   # Prepares multi-sample results or files for upload into Primary Analysis collection
   multi "${INPUT_DIRECTORY%/}" "${output}/${analysis_home}" "${MULTIQC_DIRECTORY%/}" "${REQUEST_TEMPLATE}" \
         "${repohome}/src/meta" "$dme_analysis_home" "${inputs_md5}"
-
-  # Dry-run dm_register_directory command
+ 
+  # # Dry-run dm_register_directory command
   dryrun "${output}" "${DME_REPO%/}" "/${OUTPUT_VAULT#/}"
-
+ 
   # Push to HPC DME if --dry-run option NOT provided
   if [ "$DRY_RUN" = "no" ]; then
     jobid=$(sbatch -J "pyrkit" --mem=24g --cpus-per-task=4 --time=24:00:00 \
