Adding new parsers, adding step to generate QC table, adding analysis fingerprinting step

diff --git a/pyrkit b/pyrkit
--- a/pyrkit
+++ b/pyrkit
@@ -170,6 +170,39 @@ function _get_median_tin(){
 }
 
 
+function _get_flowcell_lanes(){
+  # Parses Logfile with Information about each FastQ file
+  # @INPUT $1 = Input Directory or pipeline working directory (i.e. $INPUT_DIRECTORY)
+  # @INPUT $2 = MultiQC Output Directory
+  # @INPUT $3 = Parsed Flowcell Lanes Output file
+
+  # Performant approach to checking if glob exists using a Bash built-in function
+  if compgen -G "${1}/rpt.on.fastqs.txt" > /dev/null; then
+    echo -e "Sample\tflowcell_lanes" > ${2}/${3} || fatal "Failed to write to MultiQC Directory ${2}"
+    # Parse Flowcell Lane Information
+    sed 's/\.R1\.fastq\.gz//g' "${1}/rpt.on.fastqs.txt" | \
+      awk -v OFS='\t' '{print $1,$NF}' >> ${2}/${3}
+  fi
+}
+
+
+function _get_sample_groups(){
+  # Parses sample group information from sample.json (generated by running lint)
+  # @INPUT $1 = Input Directory containing sample.json generated by @init()
+  # @INPUT $2 = MultiQC Output Directory
+  # @INPUT $3 = Parsed Sample Group Output file
+
+  # Performant approach to checking if glob exists using a Bash built-in function
+  if compgen -G "${1}/sample.json" > /dev/null; then
+    echo -e "Sample\tTissueType"  > ${2}/${3} || fatal "Failed to write to MultiQC Directory ${2}"
+    # Parse Group informaion from sample.json with jq
+    jq -r 'to_entries[] | [.value."Sample Name", .value.Group] | @tsv' "${1}/sample.json" \
+      | sed 's/\tnan$/\tUnknown/g' >> ${2}/${3}
+  fi
+
+}
+
+
 function parse(){
   # Parse additional output files that MultiQC does not automatically parse
   # @INPUT $1 = Input Directory or pipeline working directory (i.e. $INPUT_DIRECTORY)
@@ -178,6 +211,47 @@ function parse(){
   # Parse Addtional QC metadata from logfiles
   _get_inner_distances "${1}" "${2}" "mqc_rseqc_inner_distance_plot_Percentages_parsed.txt"
   _get_median_tin "${1}" "${2}" "rseqc_median_tin.txt"
+  _get_flowcell_lanes "${1}" "${2}" "sample_flowcell_lanes.txt"
+  _get_sample_groups "${1}/DME" "${2}" "sample_group.txt"
+}
+
+
+function QC(){
+  # Aggregates MultiQC information across all samples and generates a QC Table
+  # @INPUT $1 = PATH to pyrkit/src/pyparser.py program
+  # @INPUT $2 = MultiQC Directory (i.e. $MULTIQC_DIRECTORY)
+
+  # Run in sub-shell to keep current working diretory
+  (cd "${2}"; python "${1}" "${2}"/*.txt )
+}
+
+
+function fingerprint(){
+  # Generates a Unique Identifer for an Analysis
+  # Analysis ID is determinstic and based on user inputs to pipeline
+  # @INPUT $1 = Input Directory or pipeline working directory (i.e. $INPUT_DIRECTORY)
+  # @INPUT $2 = DME base directory for all intermediate output files
+  # @RETURNS inputs_md5, analysis_id
+
+  # runinfo.txt aggregates all important user inputs, fix inconsistent delimiter
+  sed 's/^file /file\t/g' "${1}/runinfo.txt" > "${2}/run_metadata.txt"
+
+  # Convert Input Files to MD5 checksums
+  while read field value; do
+    # Get MD5 checksum if evaluating an input file
+    ifile=$(if [[ -f "$value" ]]; then md5sum "$value" | awk '{print $1}'; else echo "$value"; fi)
+    echo -e "$field\t$ifile"
+  done < <(grep -v '^jobname\|^gtf_ver\|^assembly_name\|^species' "${2}/run_metadata.txt" | sort -k2,2) \
+  > ${2}/run_inputs.md5
+
+  # Add MD5 checksum of all inputs and create an analysis id to run metadata
+  inputs_md5=$(md5sum ${2}/run_inputs.md5 | awk '{print $1}')
+  analysis_id="${inputs_md5:0:3}-${inputs_md5:${#inputs_md5}/2:2}-${inputs_md5:${#inputs_md5}-4}"
+  echo -e "md5_all_inputs\t${inputs_md5}" >> "${2}/run_metadata.txt"
+  echo -e "md5_all_inputs_serial\t${analysis_id}" >> "${2}/run_metadata.txt"
+
+  # Return inputs_md5, analysis_id
+  echo -e "${inputs_md5}\t${analysis_id}"
 }
 
 function main(){
@@ -185,7 +259,16 @@ function main(){
   # Initializes upload directory representing DME heirarchy
   # Generates collection and dataobject metadata based on inputs
   # @INPUT "$@" = command-line arguments
-  # @CALLS parser(), initialize()
+  # @CALLS require(), parser(), init(), lint(), parse(), QC(), fingerprint()
+  # @EXPORTED ARGPARSE VARIABLES:
+  #  - "Input Directory: $INPUT_DIRECTORY"
+  #  - "Output DME Vault: $OUTPUT_VAULT"
+  #  - "Request Template: $REQUEST_TEMPLATE"
+  #  - "MultiQC HOME: $MULTIQC_DIRECTORY"
+  #  - "Project ID: $PROJECT_ID"
+
+  # Check system dependencies are installed
+  require git jq python/3.5
 
   # Check for version flag
   case ${1:-} in
@@ -203,21 +286,19 @@ function main(){
   if [ $# -eq 0 ]; then parser -h; fi  # Display usage, user did not provide any args
   parser "${@}"
 
-  # Exported Argparse variables
-  #echo "Input Directory: $INPUT_DIRECTORY"
-  #echo "Output DME Vault: $OUTPUT_VAULT"
-  #echo "Request Template: $REQUEST_TEMPLATE"
-  #echo "MultiQC HOME: $MULTIQC_DIRECTORY"
-  #echo "Project ID: $PROJECT_ID"
-
   # Base directory for all intermediate output files
   output="${INPUT_DIRECTORY%/}/DME"
 
-  init output
-  require git jq python/3.5
+  # Initialize output diretory, lint template, parse logs, and aggregate QC information
+  init "${output}"
   lint "${repohome}/src/lint.py" "${REQUEST_TEMPLATE}" "${output}"
   parse "${INPUT_DIRECTORY%/}" "${MULTIQC_DIRECTORY%/}"
+  QC "${repohome}/src/pyparser.py" "${MULTIQC_DIRECTORY%/}"
 
+  # Generate unique and determinstic Analysis ID based on User Inputs
+  local inputs_md5
+  local analysis_id
+  read inputs_md5 analysis_id < <(fingerprint "${INPUT_DIRECTORY%/}" "${output}")
 }
 
 # Main: check usage, parse args, extract metadata from inputs and generate upload heirarchy
