Instantiates collection heirarchy on local filesystem and generates remaining collection and dataobject metadata

diff --git a/pyrkit b/pyrkit
--- a/pyrkit
+++ b/pyrkit
@@ -127,7 +127,7 @@ function lint(){
   # Check for basic errors and if user provided all the require metadata
   # See --request-template or $REQUEST_TEMPLATE in help for more information
   # @INPUT $1 = PATH to pyrkit/src/lint.py program
-  # @INPUT $2 = Project Request Template files to parse and lint
+  # @INPUT $2 = Project Request Template files to parse and lint (i.e. $REQUEST_TEMPLATE)
   # @INPUT $3 = Output Directory
   python ${1} ${2} ${3}
 }
@@ -231,7 +231,7 @@ function fingerprint(){
   # Analysis ID is determinstic and based on user inputs to pipeline
   # @INPUT $1 = Input Directory or pipeline working directory (i.e. $INPUT_DIRECTORY)
   # @INPUT $2 = DME base directory for all intermediate output files
-  # @RETURNS inputs_md5, analysis_id
+  # @RETURNS inputs_md5, analysis_id, assembly_name, gtf_ver
 
   # runinfo.txt aggregates all important user inputs, fix inconsistent delimiter
   sed 's/^file /file\t/g' "${1}/runinfo.txt" > "${2}/run_metadata.txt"
@@ -250,9 +250,194 @@ function fingerprint(){
   echo -e "md5_all_inputs\t${inputs_md5}" >> "${2}/run_metadata.txt"
   echo -e "md5_all_inputs_serial\t${analysis_id}" >> "${2}/run_metadata.txt"
 
-  # Return inputs_md5, analysis_id
-  echo -e "${inputs_md5}\t${analysis_id}"
+  # Get assembly_name and gtf_ver from run inputs
+  assembly_name=$((grep '^assembly_name' ${2}/run_metadata.txt || echo "custom") | awk -F '\t' '{print $NF}')
+  gtf_ver=$((grep '^gtf_ver' ${2}/run_metadata.txt || echo "custom") | awk -F '\t' '{print $NF}')
+
+  # Return inputs_md5, analysis_id, assembly_name, gtf_ver
+  echo -e "${inputs_md5}\t${analysis_id}\t${assembly_name}\t${gtf_ver}"
 }
+
+
+function collections(){
+  # Generates collection metadata and hierarchy for DME upload
+  # @INPUT $1 = PATH to pyrkit/src/initialize.py program
+  # @INPUT $2 = DME base directory for all intermediate output files
+  # @INPUT $3 = DME Vault to push data (i.e. /CCBR_Archive or /CCBR_EXT_Archive)
+  # @INPUT $4 = MultiQC Directory (i.e. $MULTIQC_DIRECTORY)
+  # @INPUT $5 = Project ID (Optional)
+  # @RETURNS ${analysis_home} or the root of the new DME collection
+
+  # Project ID may not be set if it is not provided
+  local project_id_option
+  project_id_option=${5:-}
+
+  # Creating string for optional cli argument
+  if [[ -n "${project_id_option}" ]]; then
+    project_id_option="-p ${project_id_option}"
+  fi
+
+  ( # Initializes Collection heirarchy from project metadata template
+    python "${1}" "${2}" "${2}/upload" "${3#/}" --convert \
+      -a "${2}/run_metadata.txt" \
+      -m "${4}/multiqc_matrix.tsv" \
+      ${project_id_option} 1>&2
+  )
+
+  # Return Primary Analysis Collection Name
+  analysis_home=$(cd "${2}"; find upload/PI_Lab_*/Project_*/ -type d -iname 'Primary_Analysis_*')
+  echo "${analysis_home}"
+}
+
+
+function _sym_link_fastqs(){
+  # Symlinks a Samples FastQ files into their mock upload sample collection and
+  # generates data-object metadata for DME upload
+  # @INPUT $1 = Input Directory or pipeline working directory (i.e. $INPUT_DIRECTORY)
+  # @INPUT $2 = DME base directory for all intermediate output files
+  # @INPUT $3 = DME Vault to push data (i.e. /CCBR_Archive or /CCBR_EXT_Archive)
+  # @INPUT $4 = PATH to pyrkit/src/meta program
+
+  for f in "${1}"/*.R?.fastq.gz; do
+    # Find a FastQ files mock Sample Collection
+    sample=$(basename "$f"| sed 's/\.R.\.fastq\.gz//')
+    rawdir=$(ls --color=never -d "${2}"/upload/PI_Lab_*/Project_*/Sample_*_${sample})
+    ln -s "$f" "$rawdir" || echo "Failed to create symlink for $f and $rawdir";
+    fname=$(basename "$f"); dmepath=$(dirname "$rawdir" | sed "s@^${2}/upload@${3%/}@")
+
+    # Generate dataobject metadata for FastQ files
+    python "${4}" sample -i "$rawdir/$fname" -o "$dmepath" -s "$sample"
+  done
+}
+
+
+function _sym_link_gbam(){
+  # Symlinks a Samples Genomic BAM files into their mock upload sample collection and
+  # generates data-object metadata for DME upload
+  # @INPUT $1 = Input Directory or pipeline working directory (i.e. $INPUT_DIRECTORY)
+  # @INPUT $2 = DME base directory for all intermediate output files
+  # @INPUT $3 = DME Vault to push data (i.e. /CCBR_Archive or /CCBR_EXT_Archive)
+  # @INPUT $4 = PATH to pyrkit/src/meta program
+  # @INPUT $5 = Assembly Name (i.e. mm10)
+  # @INPUT $6 = GTF Version (i.e. M21)
+  # @INPUT $7 = Short Analysis ID (i.e. f63-93-b750)
+  # @INPUT $8 = Long Analysis ID (i.e. f63ab9966e22f548934c31172388b750)
+  # @INPUT $9 = DME Primary Analysis Collection Path associated with a sample
+
+  for f in "${1}"/STAR_files/*.p2.Aligned.sortedByCoord.out.dmark.bam; do
+    # Find a FastQ files mock Sample Collection
+    sample=$(basename "$f" | sed 's/\.p2\.Aligned\.sortedByCoord\.out\.dmark\.bam$//')
+    rawdir=$(ls --color=never -d "${2}"/upload/PI_Lab_*/Project_*/Sample_*_${sample})
+    # Create renamed symlinks with assembly, gtf ver and analysis_id
+    ln -s "$f" "${rawdir}/${sample}.${5}_${6}.Aligned.toGenome.sorted.dmark.${7}.bam" \
+      || echo "Failed to create symlink for $f and $rawdir";
+    dmepath=$(dirname "$rawdir" | sed "s@^${2}/upload@${3%/}@")
+    # Generate dataobject metadata for FastQ files
+    python "${4}" sample -i "$rawdir/${sample}.${5}_${6}.Aligned.toGenome.sorted.dmark.${7}.bam" \
+      -o "$dmepath" -s "$sample" -a "${8}" -d "${9}"
+  done
+}
+
+
+function _sym_link_tbam(){
+  # Symlinks a Samples Transcriptomic BAM files into their mock upload sample collection and
+  # generates data-object metadata for DME upload
+  # @INPUT $1 = Input Directory or pipeline working directory (i.e. $INPUT_DIRECTORY)
+  # @INPUT $2 = DME base directory for all intermediate output files
+  # @INPUT $3 = DME Vault to push data (i.e. /CCBR_Archive or /CCBR_EXT_Archive)
+  # @INPUT $4 = PATH to pyrkit/src/meta program
+  # @INPUT $5 = Assembly Name (i.e. mm10)
+  # @INPUT $6 = GTF Version (i.e. M21)
+  # @INPUT $7 = Short Analysis ID (i.e. f63-93-b750)
+  # @INPUT $8 = Long Analysis ID (i.e. f63ab9966e22f548934c31172388b750)
+  # @INPUT $9 = DME Primary Analysis Collection Path associated with a sample
+
+  for f in "${1}"/bams/*.p2.Aligned.toTranscriptome.out.bam; do
+    # Find a FastQ files mock Sample Collection
+    sample=$(basename "$f" | sed 's/\.p2\.Aligned\.toTranscriptome\.out\.bam$//')
+    rawdir=$(ls --color=never -d "${2}"/upload/PI_Lab_*/Project_*/Sample_*_${sample})
+    # Create renamed symlinks with assembly, gtf ver and analysis_id
+    ln -s "$f" "${rawdir}/${sample}.${5}_${6}.Aligned.toTranscriptome.${7}.bam" \
+      || echo "Failed to create symlink for $f and $rawdir";
+    dmepath=$(dirname "$rawdir" | sed "s@^${2}/upload@${3%/}@")
+    # Generate dataobject metadata for FastQ files
+    python "${4}" sample -i "$rawdir/${sample}.${5}_${6}.Aligned.toTranscriptome.${7}.bam" \
+      -o "$dmepath" -s "$sample" -a "${8}" -d "${9}"
+  done
+}
+
+
+function links(){
+  # Creates symlinks for files to upload into DME
+  # @INPUT $1 = Input Directory or pipeline working directory (i.e. $INPUT_DIRECTORY)
+  # @INPUT $2 = DME base directory for all intermediate output files
+  # @INPUT $3 = DME Vault to push data (i.e. /CCBR_Archive or /CCBR_EXT_Archive)
+  # @INPUT $4 = PATH to pyrkit/src/meta program
+  # @INPUT $5 = Assembly Name (i.e. mm10)
+  # @INPUT $6 = GTF Version (i.e. M21)
+  # @INPUT $7 = Short Analysis ID (i.e. f63-93-b750)
+  # @INPUT $8 = Long Analysis ID (i.e. 26071405f2f1c3a6f71d4141edb208e2)
+  # @INPUT $9 = DME Primary Analysis Collection Path associated with a sample
+
+  _sym_link_fastqs "${1}" "${2}" "${3}" "${4}"
+  _sym_link_gbam "${1}" "${2}" "${3}" "${4}" "${5}" "${6}" "${7}" "${8}" "${9}"
+  _sym_link_tbam "${1}" "${2}" "${3}" "${4}" "${5}" "${6}" "${7}" "${8}" "${9}"
+}
+
+
+function fix(){
+  # Fixes formating of counts matrices to be compatible for downstream analysis
+  # @INPUT List of count matrices to reformat
+
+  for f in "${@}"; do
+    paste <(awk -F '\t' -v OFS='\t' '{print $1"|"$2}' $f | sed '1 s/gene_id|GeneName/symbol/') \
+          <(cut -f3- $f) > $f.tmp
+
+    ( # Remove suffix expected_counts from each sample name
+      head -1 $f.tmp \
+        | tr '\t' '\n' \
+        | sed 's/_expected_count$//g' \
+        | tr '\n' '\t' \
+        | sed 's/.$/\n/';
+      tail -n+2 $f.tmp
+    ) > $f.tmp2
+
+    mv $f.tmp2 $f; rm $f.tmp
+  done
+
+}
+
+
+function multi(){
+  # Prepares multi-sample results or files for upload into Primary Analysis collection
+  # @INPUT $1 = Input Directory or pipeline working directory (i.e. $INPUT_DIRECTORY)
+  # @INPUT $2 = Path to Primary Analysis Collection directory on local filesystem
+  # @INPUT $3 = MultiQC Directory (i.e. $MULTIQC_DIRECTORY)
+  # @INPUT $4 = Project Request Template (i.e. $REQUEST_TEMPLATE)
+  # @INPUT $5 = PATH to pyrkit/src/meta program
+  # @INPUT $6 = DME Primary Analysis Collection Path
+  # @INPUT $7 = Long Analysis ID (i.e. f63ab9966e22f548934c31172388b750)
+
+
+  # Add Counts Matrices (Gene and Isoform Counts), TIN counts, MultiQC Report and TSV, Project Request Spreadsheet
+  cp "${1}/DEG_ALL/RSEM.genes.expected_count.all_samples.txt" "${2}/RSEM_genes_expected_counts.tsv"
+  cp "${1}/DEG_ALL/RSEM.isoforms.expected_count.all_samples.txt" "${2}/RSEM_isoforms_expected_counts.tsv"
+
+  # Reformat for downstream analysis and remove suffix expected_counts
+  fix "${2}/RSEM_genes_expected_counts.tsv" "${2}/RSEM_isoforms_expected_counts.tsv"
+
+  # Symlink remaining files to Primary Analysis collection
+  mqc_prefix=$(basename ${1})
+  for f in "${3}"/multiqc_matrix.tsv "${1}/${mqc_prefix}_multiqc_report.html" "${4}"; do
+    ln -s "${f}" "${2}/" || echo "Failed to create symlink for $f and ${2}";
+  done
+
+  # Generate dataobject metadata files for aggregate or multi-sample data
+  for f in $(find "${2}" -not -type d -not -iname '*.metadata.json'); do
+    python "${5}" combined -i "$f" -o "${6}" -a "${7}"
+  done
+}
+
 
 function main(){
   # Parses cli args using argparse.bash and input files to extract metadata for upload
@@ -261,14 +446,17 @@ function main(){
   # @INPUT "$@" = command-line arguments
   # @CALLS require(), parser(), init(), lint(), parse(), QC(), fingerprint()
   # @EXPORTED ARGPARSE VARIABLES:
-  #  - "Input Directory: $INPUT_DIRECTORY"
-  #  - "Output DME Vault: $OUTPUT_VAULT"
-  #  - "Request Template: $REQUEST_TEMPLATE"
-  #  - "MultiQC HOME: $MULTIQC_DIRECTORY"
-  #  - "Project ID: $PROJECT_ID"
+  #   $INPUT_DIRECTORY = Input Directory
+  #   $OUTPUT_VAULT    = Output DME Vault
+  #   $REQUEST_TEMPLATE  = Request Template
+  #   $MULTIQC_DIRECTORY = MultiQC HOME
+  #   $PROJECT_ID"  =  Project ID
 
   # Check system dependencies are installed
   require git jq python/3.5
+
+  # Set Defaults for Optional arguments
+  PROJECT_ID="${PROJECT_ID:-}"
 
   # Check for version flag
   case ${1:-} in
@@ -296,10 +484,24 @@ function main(){
   QC "${repohome}/src/pyparser.py" "${MULTIQC_DIRECTORY%/}"
 
   # Generate unique and determinstic Analysis ID based on User Inputs
-  local inputs_md5
-  local analysis_id
-  read inputs_md5 analysis_id < <(fingerprint "${INPUT_DIRECTORY%/}" "${output}")
+  local inputs_md5 analysis_id
+  local assembly_name gtf_ver
+  IFS=$'\t' read inputs_md5 analysis_id assembly_name gtf_ver < <(fingerprint "${INPUT_DIRECTORY%/}" "${output}")
+
+  # Initializes local filesystem mock DME hierarchy
+  # PI-, Project-, Analysis-, Sample-level directories are created along with metadata
+  analysis_home=$(collections "${repohome}/src/initialize.py" "${output}" "${OUTPUT_VAULT%/}" "${MULTIQC_DIRECTORY%/}" "${PROJECT_ID}")
+  dme_analysis_home=$(echo "$analysis_home" | sed "s@^upload@${OUTPUT_VAULT%/}@")
+
+  # Creates symlinks for sample-level collections in DME
+  links "${INPUT_DIRECTORY%/}" "${output}" "${OUTPUT_VAULT%/}" "${repohome}/src/meta" \
+        "${assembly_name}" "${gtf_ver}" "${analysis_id}" "${inputs_md5}" "${dme_analysis_home}"
+
+  # Prepares multi-sample results or files for upload into Primary Analysis collection
+  multi "${INPUT_DIRECTORY%/}" "${output}/${analysis_home}" "${MULTIQC_DIRECTORY%/}" "${REQUEST_TEMPLATE}" \
+        "${repohome}/src/meta" "$dme_analysis_home" "${inputs_md5}"
 }
+
 
 # Main: check usage, parse args, extract metadata from inputs and generate upload heirarchy
 main "$@"
